# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: DNSControl Action (Official)
description: The Official DNSControl GitHub Action.
author: Eli Heady <eli.heady@gmail.com>

branding:
  icon: 'sliders'
  color: 'blue'

inputs:

  check:
    default: 'false'
    description: Run `dnscontrol check` before any other commands - default is 'false'
    required: false

  version:
    default: 'latest'
    description: Desired version to run (default 'latest')
    required: false

  cmdargs:
    description: DNSControl command and optional arguments
    required: true

  dnsconfig_file:
    default: dnsconfig.js
    description: Path to dnsconfig.js. Defaults to 'dnsconfig.js' (at repository root)
    required: false

  creds_file:
    default: creds.json
    description: Path to creds.json. Defaults to 'creds.json' (at repository root)
    required: false

  output_file:
    default: ''
    description: Write DNSControl output to this file
    required: false

  post_pr_comment:
    default: 'false'
    description: Post the DNSControl output in a PR comment (default 'false')
    required: false

  post_summary:
    default: 'false'
    description: Post the DNSControl output in the step summary (default 'false')
    required: false

outputs:
  output:
    description: DNSControl output
    value: ${{ steps.dnscontrol.outputs.output }}
  output_file:
    description: DNSControl output written to file
    value: ${{ steps.write_file.outputs.output_file }}


runs:
  using: composite
  steps:

    - name: Check Runner OS
      if: ${{ runner.os != 'Linux' && runner.os != 'Windows' && runner.os != 'macOS'}}
      shell: bash
      run: |
        echo "::error title=error::Action supports Linux, Windows, and macOS only"
        exit 1

    - name: Debug Helpers
      shell: bash
      env:
        DEBUG_ACTION: ${{ env.DEBUG_ACTION }}
      run: |
        # Debug Helpers
        if [[ "${DEBUG_ACTION}" == "true" ]]; then
          echo "DEBUG=echo" >>"$GITHUB_ENV"
        else
          # we're setting DEBUG var to the shell builtin `true` if DEBUG_ACTION
          # var was not 'true' to make the debug statements no-ops. it's confusing, sorry.
          echo "DEBUG=true" >>"$GITHUB_ENV"
        fi
        if [[ -n "$FORGEJO_REPOSITORY" ]]; then
          echo "FJECHO=echo" >>"$GITHUB_ENV"
        else
          # do not echo if we're not on a Forgejo Actions runner
          # same as above, use shell builtin `true` to no-op the $FJECHO statements with exit 0 return
          echo "FJECHO=true" >>"$GITHUB_ENV"
        fi

    - name: Sanitize inputs
      env:
        DNSCONTROL_VERSION: ${{ inputs.version }}
        OUTPUT_FILE: ${{ inputs.output_file }}
        DNSCONFIG_FILE: ${{ inputs.dnsconfig_file }}
        CREDS_FILE: ${{ inputs.creds_file }}
        CMDARGS: ${{ inputs.cmdargs }}
      shell: bash
      run: |
        # Sanitize inputs
        $FJECHO "Sanitize inputs"
        set +e
        echo "OUTPUT_FILE=$OUTPUT_FILE" >>"$GITHUB_ENV"

        if [[ ! -e "$DNSCONFIG_FILE" ]]; then
          echo "the specified dnsconfig_file \"$DNSCONFIG_FILE\" does not exist in workspace"
          exit 1
        fi
        echo "DNSCONFIG_FILE=$DNSCONFIG_FILE" >>"$GITHUB_ENV"

        if [[ ! -e "$CREDS_FILE" ]]; then
          echo "the specified creds_file \"$CREDS_FILE\" does not exist in workspace"
          exit 1
        fi
        echo "CREDS_FILE=$CREDS_FILE" >>"$GITHUB_ENV"

        if [[ ! "$DNSCONTROL_VERSION" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+(-[\-_a-zA-Z0-9]*)?$ ]]; then
          if [[ "$DNSCONTROL_VERSION" != "latest" ]]; then
            echo "invalid DNSControl version format \"$DNSCONTROL_VERSION\""
            exit 1
          fi
        fi
        if [[ "$DNSCONTROL_VERSION" != "latest" ]]; then
          [[ $DNSCONTROL_VERSION != "v"* ]] && DNSCONTROL_VERSION="v$DNSCONTROL_VERSION"
        fi
        echo "DNSCONTROL_VERSION=$DNSCONTROL_VERSION" >>"$GITHUB_ENV"

        # set default curl args
        CURL="curl -fsS --retry 5 --retry-max-time 30 -H user-agent:official-dnscontrol-action -H X-GitHub-Api-Version:2022-11-28"
        CURLJSON="$CURL -H Accept:application/vnd.github.v3+json,application/json"
        
        echo "CURL=$CURL" >>"$GITHUB_ENV"
        echo "CURLJSON=$CURLJSON" >>"$GITHUB_ENV"

        # selectively append `--creds` to commands that need it
        read -ra ARGS_SPLIT <<< "$CMDARGS"
        case "${ARGS_SPLIT[0]}" in
          preview | push | check-creds)
            CREDS_ARG="--creds $CREDS_FILE"
          ;;
          *)
            CREDS_ARG=""
          ;;
        esac
        echo "CREDS_ARG=$CREDS_ARG" >>"$GITHUB_ENV"

    - name: Resolve Comment Helpers
      shell: bash
      if: ${{ inputs.post_pr_comment == 'true' }}
      id: comment_api
      env:
        REPO: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        # Resolve Comment Helpers
        $FJECHO "Resolve Comment Helpers"

        echo "marker=<!-- dnscontrol-action -->" >>"$GITHUB_OUTPUT"

        GIT_HOST=$(git config --get remote.origin.url | sed -E 's|.*@([^/:]+).*|\1|; s|.*://([^/]+).*|\1|')

        if [[ $GIT_HOST == "github.com" ]]; then
          API_URL="https://api.github.com"
          API_PAGER="per_page"
          PAGE_LIMIT=50
          echo "supported=true" >>"$GITHUB_OUTPUT"
        elif [[ -n "$FORGEJO_REPOSITORY" ]]; then
          API_URL="https://${GIT_HOST}/api/v1"
          # note comment pagination not supported on Forgejo
          echo "supported=true" >>"$GITHUB_OUTPUT"
        else
          echo "NOTICE: API is unknown for git host \"$GIT_HOST\" - PR comments disabled"
          echo "supported=false" >>"$GITHUB_OUTPUT"
        fi

        PR_API_URL="${API_URL}/repos/$REPO/issues/$PR_NUMBER/comments"
        COMMENT_API_URL="${API_URL}/repos/$REPO/issues/comments"

        echo "PR_API_URL=$PR_API_URL" >>"$GITHUB_ENV"
        echo "COMMENT_API_URL=$COMMENT_API_URL" >>"$GITHUB_ENV"
        echo "API_PAGER=$API_PAGER" >>"$GITHUB_ENV"
        echo "PAGE_LIMIT=$PAGE_LIMIT" >>"$GITHUB_ENV"

    - name: Resolve OS and Arch
      env:
        RUNNER_OS: ${{ runner.os }}
        RUNNER_ARCH: ${{ runner.arch }}
      shell: bash
      run: |
        # Resolve OS and Arch
        $FJECHO "Resolve OS and Arch"
        case "$RUNNER_OS" in
          Linux)
            OS='linux'
            EXT='tar.gz'
          ;;
          Windows)
            OS='windows'
            EXT='zip'
          ;;
          macOS)
            OS='darwin'
            EXT='tar.gz'
          ;;
          *)
            echo "::error title=error::unsupported runner.os \"$RUNNER_OS\""
            exit 1
          ;;
        esac

        case "$RUNNER_ARCH" in
          X64 | x86_64)
            ARCH='amd64'
          ;;
          ARM64 | aarch64)
            ARCH='arm64'
          ;;
          *)
            echo "::error title=error::unsupported runner.arch \"$RUNNER_ARCH\""
            exit 1
          ;;
        esac

        if [[ "$OS" == "darwin" ]]; then
          ARCH=all
        fi

        echo "ARCH=$ARCH" >>"$GITHUB_ENV"
        echo "OS=$OS" >>"$GITHUB_ENV"
        echo "EXT=$EXT" >>"$GITHUB_ENV"


    - name: Resolve download URL for latest
      if: ${{ inputs.version == 'latest' }}
      shell: bash
      run: |
        # Resolve download URL for latest
        $FJECHO "Resolve download URL for latest"
        LATEST=$($CURLJSON -L https://api.github.com/repos/DNSControl/dnscontrol/releases/latest)
        VERSION=$(printf '%s' $LATEST | jq -r ".tag_name")
        echo "resolved latest version: $VERSION"

        PACKAGE=dnscontrol_${VERSION#v}_${OS}_${ARCH}.${EXT}
        URL=$(\
          printf '%s' $LATEST \
          | jq -r --arg package $PACKAGE '.assets[] | select(.name == "\($package)") | .browser_download_url'\
        )
        echo "resolved package url: $URL"
        echo "URL=$URL" >>"$GITHUB_ENV"

    - name: Resolve download URL
      if: ${{ inputs.version != 'latest' }}
      shell: bash
      run: |
        # Resolve download URL
        $FJECHO "Resolve download URL"
        PACKAGE=dnscontrol_${DNSCONTROL_VERSION#v}_${OS}_${ARCH}.${EXT}
        URL=$(\
          $CURLJSON -L https://api.github.com/repos/DNSControl/dnscontrol/releases \
          | jq -r --arg version $DNSCONTROL_VERSION --arg package $PACKAGE \
            '.[] | select(.tag_name == "\($version)") | .assets[] | select(.name == "\($package)") | .browser_download_url' \
        )
        if [[ -z "$URL" ]]; then
          echo "could not find version \"$DNSCONTROL_VERSION\""
          exit 1
        fi
        echo "resolved package url: $URL"
        echo "URL=$URL" >>"$GITHUB_ENV"

    - name: Download DNSControl
      id: download
      shell: bash
      env:
        TEMP: ${{ runner.temp }}
      run: |
        # Download DNSControl
        $FJECHO "Download DNSControl"
        $CURL -H "Accept: application/octet-stream" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -L "${URL}" -o "$TEMP/dnscontrol.$EXT"
        echo "file=$TEMP/dnscontrol.$EXT" >>"$GITHUB_OUTPUT"

    - name: Unpack DNSControl
      if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      shell: bash
      env:
        TEMP: ${{ runner.temp }}
        PACKAGE: ${{ steps.download.outputs.file }}
      run: |
        # Unpack DNSControl - Linux or macOS
        $FJECHO "Unpack DNSControl - Linux or macOS"
        RESOLVED_TEMP="$(readlink -f $TEMP)/dnscontrol$RANDOM"
        mkdir -p "$RESOLVED_TEMP"
        tar -C "$RESOLVED_TEMP" -xvzf $PACKAGE dnscontrol
        echo "$RESOLVED_TEMP" >>"$GITHUB_PATH"
        $RESOLVED_TEMP/dnscontrol version
        echo "DNSCONTROL=$RESOLVED_TEMP/dnscontrol" >>"$GITHUB_ENV"

    - name: Unpack DNSControl
      if: ${{ runner.os == 'Windows' }}
      shell: bash
      env:
        TEMP: ${{ runner.temp }}
        PACKAGE: ${{ steps.download.outputs.file }}
      run: |
        # Unpack DNSControl - Windows
        $FJECHO "Unpack DNSControl - Windows"
        RESOLVED_TEMP="$TEMP/dnscontrol$RANDOM" # windows lacks readlink, so this may be relative
        mkdir -p "$RESOLVED_TEMP"
        unzip -d "$RESOLVED_TEMP" $PACKAGE dnscontrol.exe
        echo "$RESOLVED_TEMP" >>"$GITHUB_PATH"
        $RESOLVED_TEMP/dnscontrol.exe version
        echo "DNSCONTROL=$RESOLVED_TEMP/dnscontrol.exe" >>"$GITHUB_ENV"

    - name: DNSControl check
      if: ${{ inputs.check == 'true' }}
      continue-on-error: true
      id: check
      shell: bash
      env:
        NO_COLOR: 'true'
      run: |
        # DNSControl check
        $FJECHO "DNSControl check"
        set +e
        TMP_OUT="$(mktemp)"
        $DNSCONTROL check --config "$DNSCONFIG_FILE" 2>&1 | tee "$TMP_OUT"
        err=${PIPESTATUS[0]}

        DELIMITER="DNSCONTROL-$RANDOM"
        {
          echo "output<<$DELIMITER"
          cat "$TMP_OUT"
          echo "$DELIMITER"
        } >>"$GITHUB_OUTPUT"
        rm -f "$TMP_OUT"
        exit $err

    - name: Attach Check Results as PR comment
      # execute if comment api is supported, user set post_pr_comment=true, this is a PR event, AND dnscontrol check ran and failed
      if: ${{
             steps.comment_api.outputs.supported == 'true' &&
             inputs.post_pr_comment == 'true' &&
             github.event.pull_request.number != '' &&
             (
               steps.check.outcome != 'skipped' &&
               steps.check.outcome != 'success'
             ) }}
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
        API_TOKEN: ${{ github.token }}
        MARKER: ${{ steps.comment_api.outputs.marker }}
        STEP_TITLE: "Attach Check Results as PR comment"
        COMMENT_BODY: |
          <details open><summary>DNSControl Check Results</summary>

          ### DNSControl Check Results

          ```
          ${{ steps.check.outputs.output }}
          ```
          </details>
          ${{ steps.comment_api.outputs.marker }}
      run: "$ACTION_PATH/bin/comment.sh"

    - name: Check Summary
      # write check output to job summary if check failed
      if: ${{ steps.check.outcome != 'success' && steps.check.outcome != 'skipped' }}
      shell: bash
      env:
        OUTPUT: ${{ steps.check.outputs.output }}
      run: |
        # Check Summary
        $FJECHO "Check Summary"
        echo "$OUTPUT" >>"$GITHUB_STEP_SUMMARY"
        # check failed, stop the job
        exit 1

    - name: Run DNSControl (VIEW OUTPUT HERE)
      id: dnscontrol
      # execute only if check was ok or skipped
      if: ${{ steps.check.outcome == 'success' || steps.check.outcome == 'skipped' }}
      continue-on-error: true
      shell: bash
      env:
        DNSCONTROL_COMMAND: ${{ inputs.cmdargs }}
      run: |
        # DNSControl
        $FJECHO "DNSControl"
        set +e
        TMP_OUT="$(mktemp)"
        $DNSCONTROL --no-colors $DNSCONTROL_COMMAND --config "$DNSCONFIG_FILE" $CREDS_ARG 2>&1 | tee "$TMP_OUT"
        err=${PIPESTATUS[0]}

        DELIMITER="DNSCONTROL-$RANDOM"
        {
          echo "output<<$DELIMITER"
          cat "$TMP_OUT"
          echo "$DELIMITER"
        } >>"$GITHUB_OUTPUT"
        rm -f "$TMP_OUT"
        exit $err

    - name: Write output file
      id: write_file
      # execute if user specified an output file AND dnscontrol job ran
      if: ${{ inputs.output_file != '' && steps.dnscontrol.outcome != 'skipped' }}
      shell: bash
      env:
        OUTPUT_FILE: ${{ inputs.output_file }}
        OUTPUT: ${{ steps.dnscontrol.outputs.output }}
      run: |
        # Write output file
        $FJECHO "Write output file"
        echo "$OUTPUT" > "$OUTPUT_FILE"
        echo "output_file=$OUTPUT_FILE" >>"$GITHUB_OUTPUT"

    - name: Attach Results as PR comment
      # execute if comment api is supported, user set post_pr_comment=true, this is a PR event, AND dnscontrol command ran
      if: ${{
             steps.comment_api.outputs.supported == 'true' &&
             inputs.post_pr_comment == 'true' &&
             github.event.pull_request.number != '' &&
             steps.dnscontrol.outcome != 'skipped' }}
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
        API_TOKEN: ${{ github.token }}
        MARKER: ${{ steps.comment_api.outputs.marker }}
        STEP_TITLE: "Attach Results as PR comment"
        COMMENT_BODY: |
          <details open><summary>DNSControl Results</summary>

          ### DNSControl Results

          ```
          ${{ steps.dnscontrol.outputs.output }}
          ```
          </details>
          ${{ steps.comment_api.outputs.marker }}
      run: "$ACTION_PATH/bin/comment.sh"

    - name: Job Summary
      id: job_summary
      # execute if user set post_summary AND dnscontrol job ran
      if: ${{ inputs.post_summary == 'true' && steps.dnscontrol.outcome != 'skipped' }}
      shell: bash
      env:
        OUTPUT: ${{ steps.dnscontrol.outputs.output }}
      run: |
        # Job Summary
        $FJECHO "Job Summary"
        echo "$OUTPUT" >>"$GITHUB_STEP_SUMMARY"

    - name: Action failed
      if: ${{ steps.dnscontrol.outcome != 'skipped' && steps.dnscontrol.outcome != 'success' }}
      shell: bash
      run: |
        # Action failed
        $FJECHO "Action failed"
        echo "::error title=error::DNSControl command failed"
        exit 1
